import MySQLdb as mdb

db = mdb.connect('localhost', 'root', 'admin', 'db_stuff')


def seed_heroes():
	heroes = [
		("Abbadon", ""),
		("Alchemist", ""),
		("Ancient Apparition", ""),
		("Anti-Mage", ""),
		("Axe", ""),
		("Bane", ""),
		("Batrider", ""),
		("Beastmaster", ""),
		("Bloodseeker", ""),
		("Bounty Hunter", ""),
		("Brewmaster", ""),
		("Bristleback", ""),
		("Broodmother", ""),
		("Centaur Warrunner", ""),
		("Chaos Knight", ""),
		("Chen", ""),
		("Clinkz", ""),
		("Clockwerk", ""),
		("Crystal Maiden", ""),
		("Dark Seer", ""),
		("Dazzle", ""),
		("Death Prophet", ""),
		("Disruptor", ""),
		("Doom", ""),
		("Dragon Knight", ""),
		("Drow Ranger", ""),
		("Earth Spirit", ""),
		("Earthshaker", ""),
		("Elder Titan", ""),
		("Ember Spirit", ""),
		("Enchantress", ""),
		("Enigma", ""),
		("Faceless Void", ""),
		("Gyrocopter", ""),
		("Huskar", ""),
		("Invoker", ""),
		("Io", ""),
		("Jakiro", ""),
		("Juggernaut", ""),
		("Keeper of the Light", ""),
		("Kunkka", ""),
		("Legion Commander", ""),
		("Leshrac", ""),
		("Lich", ""),
		("Lifestealer", ""),
		("Lina", ""),
		("Lion", ""),
		("Lone Druid", ""),
		("Luna", ""),
		("Lycan", ""),
		("Magnus", ""),
		("Medusa", ""),
		("Meepo", ""),
		("Mirana", ""),
		("Morphling", ""),
		("Naga Siren", ""),
		("Nature's Prophet", ""),
		("Necrophos", ""),
		("Night Stalker", ""),
		("Nyx Assasin", ""),
		("Ogre Magi", ""),
		("Omniknight", ""),
		("Oracle", ""),
		("Outworld Devourer", ""),
		("Phantom Assasin", ""),
		("Phantom Lancer", ""),
		("Phoenix", ""),
		("Puck", ""),
		("Pudge", ""),
		("Pugna", ""),
		("Queen of Pain", ""),
		("Razor", ""),
		("Riki", ""),
		("Rubick", ""),
		("Sand King", ""),
		("Shadow Demon", ""),
		("Shadow Fiend", ""),
		("Shadow Shaman", ""),
		("Silencer", ""),
		("Skywrath Mage", ""),
		("Slardar", ""),
		("Slark", ""),
		("Sniper", ""),
		("Spectre", ""),
		("Spirit Breaker", ""),
		("Storm Spirit", ""),
		("Sven", ""),
		("Techies", ""),
		("Templar Assasin", ""),
		("Terrorblade", ""),
		("Tidehunter", ""),
		("Timbersaw", ""),
		("Tinker", ""),
		("Tiny", ""),
		("Treant Protector", ""),
		("Troll Warlord", ""),
		("Tusk", ""),
		("Undying", ""),
		("Ursa", ""),
		("Vengeful Spirit", ""),
		("Venomancer", ""),
		("Viper", ""),
		("Visage", ""),
		("Warlock", ""),
		("Weaver", ""),
		("Windranger", ""),
		("Winter Wyvern", ""),
		("Witch Doctor", ""),
		("Wraith King", ""),
		("Zeus", "")
		]
	c = db.cursor()
	statement = "INSERT INTO Heroes (name, description) VALUES (%s, %s)"
	c.executemany(statement, heroes)
	db.commit()
		
def seed_patch():
	c = db.cursor()
	patches = [
		('6.84', ),
		('6.83', ),
		('6.82', ),
		('6.81', ),
		('6.80', ),
		('6.79', ),
		('6.78', ),
		('6.77', ),
		('6.76', ),
		('6.75', )
		]
	statement = "INSERT INTO Patch (patch) VALUES (%s)"
	c.executemany(statement, patches)
	db.commit()

if __name__ == '__main__':
	seed_heroes()		
	seed_patch()